import CardEarlyOutReminder from "../(page)/home/dashboard/CardEarlyOutReminder";

const appString = {
    authTitle: 'Welcome to',
    appNameFull: 'Teqheal Solution',
    appName1: 'Teqheal',
    appName2: 'Solution',
    empSystem: 'Employee Management System',
    authDes: 'Connecting People. Optimizing Process. Enhancing Performance.',
    authCoreValue: 'Core Values',
    coreV1: 'Working Everyday Towards Perfection',
    coreV2: 'Grow Consistently Every Day',
    coreV3: 'Inspiring Teams To Build The Best',
    coreV4: 'Creating Value Adding Services',
    signUpTitle: 'Create New Account',
    signUpDes: 'Let\'s register and connect with your co-workers to get the things done together and faster.',
    signInTitle: 'Sign In Your Account',
    signInDes: 'Welcome Back! Please Sign In to access product.',
    alreadyAcc: 'Already have an account?',
    dontAcc: 'Don’t have an account?',
    agreeWith: 'Agree with',
    termsAndC: 'Terms & Condition',
    privacyP: 'Privacy Policy',
    forgotPassword: 'Forgot Password?',
    forgotPasswordDes: 'Enter the email address associated with your account and we will send you the link to reset password.',
    rememberPassword: 'Remember Password?',
    signUp: 'Sign Up',
    signIn: 'Sign In',
    login: 'Login',
    submit: 'Submit',
    empCode: 'EMP Code',
    fullName: 'Full Name',
    emailAddress: 'Email Address',
    mobileNumber: 'Mobile Number',
    dateOfBirth: 'Date Of Birth',
    role: 'Role',
    status: 'Status',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    fullNameV1: 'Please enter your full name!',
    emailAddressV1: 'Please enter your email!',
    emailAddressV2: 'Invalid email format',
    mobileNumberV1: 'Please enter your mobile number',
    mobileNumberV2: 'Invalid mobile number format',
    passwordV1: 'Please enter your password!',
    passwordV2: 'Password must start with an uppercase letter.',
    passwordV3: 'Password must contain at least one number.',
    passwordV4: 'Password must contain at least one special character.',
    passwordV5: 'Password must be at least 8 characters long.',
    confirmPasswordV1: 'Please enter your confirm password!',
    confirmPasswordV2: 'Password do not matched!',
    hey: 'Hey',
    motiveLine: 'Have a productive and amazing day!',
    clockInOut: 'Clock In / Out',
    startTracking: 'Start Tracking',
    stopTracking: 'Stop Tracking',
    clockIn: 'Clock In',
    clockOut: 'Clock Out',
    breakIn: 'Break In',
    breakOut: 'Break Out',
    totalTime: 'Total Time',
    workingTime: 'Working Time',
    breakTime: 'Break Time',
    liveTracking: 'Live Tracking',
    todayActivity: 'Today Activity',
    earlyOutReminder: 'Early Out Reminder',
    attendanceReport: 'Attendance Report',
    leaveReport: 'Leave Report',
    noticeBoard: 'Notice Board',
    action: 'Action',
    delete: 'Delete',
    deleteConfirmation: 'Sure to delete?',
    approveConfirmation: 'Sure to Approve this user?',
    approve: 'Approve',
    rejectConfirmation: 'Sure to Reject this user?',
    edit: 'Edit',
    view: 'View',
    reject: 'Reject',
    empSearchHint: 'Search by name, email or mobile',
    attReportSearchHint: 'Search by name',
    approvalStatus: 'Approval Status',
    isActive: 'Active',
    emergencyContactNo: 'Emergency Contact No',
    technology: 'Technology',
    gender: 'Gender',
    bloodGroup: 'Blood Group',
    skills: 'Skills',
    address: 'Address',
    pincode: 'Pincode',
    aadharNumber: 'Aadhar Number',
    panNumber: 'PAN Number',
    bankAccountNumber: 'Bank Account Number',
    ifscCode: 'IFSC Code',
    dateOfJoining: 'Date of Joining',
    dateOfLeaving: 'Date of Leaving',
    financialDetails: 'Financial Details',
    admin: 'Admin',
    employee: 'Employee',
    male: 'Male',
    female: 'Female',
    other: 'Other',
    empStatus: 'Employee Status',
    personalDetails: 'Personal Details',
    profileDetails: 'Profile Details',
    active: 'Active',
    addRecord: 'Add Record',
    updateRecord: 'Update Record',
    addEmployee: 'Add Employee',
    updateEmployee: 'Update Employee',
    profileUrl: 'Profile Url',
    profile: 'Profile',
    userName: 'User Name',
    totalHours: 'Total Hours',
    workingHours: 'Working Hours',
    breakHours: 'Break Hours',
    lateArrival: 'Late Arrival',
    overtime: 'Overtime',
    screenshots: 'Screenshots',
    eventCount: 'Event Count',
    userDetail: 'User Detail',
};

export default appString;